#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 81
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 3

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  sym_opcode = 2,
  sym_identifier = 3,
  anon_sym_COMMA = 4,
  aux_sym_operand_token1 = 5,
  anon_sym_COLON = 6,
  anon_sym_DOT = 7,
  anon_sym_DOTinclude = 8,
  anon_sym_DOTproc = 9,
  anon_sym_DOTendproc = 10,
  sym_immediate = 11,
  sym_string = 12,
  anon_sym_SEMI = 13,
  aux_sym_line_comment_token1 = 14,
  sym_block_comment = 15,
  anon_sym_LF = 16,
  sym_program = 17,
  sym_section = 18,
  sym__section_body = 19,
  sym_subsection = 20,
  sym_subsection_body = 21,
  sym_instruction = 22,
  sym_constant = 23,
  sym_operands = 24,
  sym_operand = 25,
  sym_label = 26,
  sym_sublabel = 27,
  sym_macro = 28,
  sym_macro_include = 29,
  sym_macro_proc = 30,
  sym_line_comment = 31,
  aux_sym_program_repeat1 = 32,
  aux_sym_section_repeat1 = 33,
  aux_sym_subsection_repeat1 = 34,
  aux_sym_macro_proc_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [sym_opcode] = "opcode",
  [sym_identifier] = "identifier",
  [anon_sym_COMMA] = ",",
  [aux_sym_operand_token1] = "operand_token1",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT] = ".",
  [anon_sym_DOTinclude] = ".include",
  [anon_sym_DOTproc] = ".proc",
  [anon_sym_DOTendproc] = ".endproc",
  [sym_immediate] = "immediate",
  [sym_string] = "string",
  [anon_sym_SEMI] = ";",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [sym_block_comment] = "block_comment",
  [anon_sym_LF] = "\n",
  [sym_program] = "program",
  [sym_section] = "section",
  [sym__section_body] = "_section_body",
  [sym_subsection] = "subsection",
  [sym_subsection_body] = "subsection_body",
  [sym_instruction] = "instruction",
  [sym_constant] = "constant",
  [sym_operands] = "operands",
  [sym_operand] = "operand",
  [sym_label] = "label",
  [sym_sublabel] = "sublabel",
  [sym_macro] = "macro",
  [sym_macro_include] = "macro_include",
  [sym_macro_proc] = "macro_proc",
  [sym_line_comment] = "line_comment",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_section_repeat1] = "section_repeat1",
  [aux_sym_subsection_repeat1] = "subsection_repeat1",
  [aux_sym_macro_proc_repeat1] = "macro_proc_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_opcode] = sym_opcode,
  [sym_identifier] = sym_identifier,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_operand_token1] = aux_sym_operand_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DOTinclude] = anon_sym_DOTinclude,
  [anon_sym_DOTproc] = anon_sym_DOTproc,
  [anon_sym_DOTendproc] = anon_sym_DOTendproc,
  [sym_immediate] = sym_immediate,
  [sym_string] = sym_string,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [sym_block_comment] = sym_block_comment,
  [anon_sym_LF] = anon_sym_LF,
  [sym_program] = sym_program,
  [sym_section] = sym_section,
  [sym__section_body] = sym__section_body,
  [sym_subsection] = sym_subsection,
  [sym_subsection_body] = sym_subsection_body,
  [sym_instruction] = sym_instruction,
  [sym_constant] = sym_constant,
  [sym_operands] = sym_operands,
  [sym_operand] = sym_operand,
  [sym_label] = sym_label,
  [sym_sublabel] = sym_sublabel,
  [sym_macro] = sym_macro,
  [sym_macro_include] = sym_macro_include,
  [sym_macro_proc] = sym_macro_proc,
  [sym_line_comment] = sym_line_comment,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
  [aux_sym_subsection_repeat1] = aux_sym_subsection_repeat1,
  [aux_sym_macro_proc_repeat1] = aux_sym_macro_proc_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_opcode] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_operand_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOTinclude] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOTproc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOTendproc] = {
    .visible = true,
    .named = false,
  },
  [sym_immediate] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym__section_body] = {
    .visible = false,
    .named = true,
  },
  [sym_subsection] = {
    .visible = true,
    .named = true,
  },
  [sym_subsection_body] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_operands] = {
    .visible = true,
    .named = true,
  },
  [sym_operand] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_sublabel] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_include] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_proc] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subsection_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_proc_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
  [1] =
    {field_body, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 5,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 7,
  [11] = 8,
  [12] = 9,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 16,
  [19] = 15,
  [20] = 17,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 23,
  [31] = 31,
  [32] = 32,
  [33] = 29,
  [34] = 32,
  [35] = 35,
  [36] = 35,
  [37] = 37,
  [38] = 26,
  [39] = 39,
  [40] = 24,
  [41] = 25,
  [42] = 27,
  [43] = 21,
  [44] = 28,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 46,
  [50] = 50,
  [51] = 50,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 45,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 65,
  [68] = 68,
  [69] = 59,
  [70] = 58,
  [71] = 71,
  [72] = 63,
  [73] = 73,
  [74] = 71,
  [75] = 64,
  [76] = 60,
  [77] = 68,
  [78] = 73,
  [79] = 66,
  [80] = 48,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '\n', 53,
        '"', 3,
        '$', 22,
        ',', 35,
        '.', 38,
        '/', 4,
        ':', 37,
        ';', 45,
        '=', 26,
        '@', 23,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F')) ADVANCE(31);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      if (lookahead == '-' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(34);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '$') ADVANCE(22);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ';') ADVANCE(45);
      if (lookahead == '@') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      if (lookahead == '-' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ';') ADVANCE(45);
      if (lookahead == '@') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(34);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(52);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(41);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(42);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(43);
      END_STATE();
    case 23:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ';') ADVANCE(45);
      if (lookahead == '@') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(24);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(34);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_opcode);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      if (lookahead == '-' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_opcode);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F')) ADVANCE(31);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      if (lookahead == '-' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(34);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F')) ADVANCE(31);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      if (lookahead == '-' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(34);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      if (lookahead == '-' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_operand_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == 'e') ADVANCE(14);
      if (lookahead == 'i') ADVANCE(15);
      if (lookahead == 'p') ADVANCE(19);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == 'i') ADVANCE(15);
      if (lookahead == 'p') ADVANCE(19);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOTinclude);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DOTproc);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DOTendproc);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_immediate);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '*') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == ';') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 24},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 24},
  [8] = {.lex_state = 24},
  [9] = {.lex_state = 24},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 24},
  [14] = {.lex_state = 24},
  [15] = {.lex_state = 24},
  [16] = {.lex_state = 24},
  [17] = {.lex_state = 24},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 24},
  [24] = {.lex_state = 24},
  [25] = {.lex_state = 24},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 24},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 24},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 24},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 24},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 24},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 24},
  [44] = {.lex_state = 24},
  [45] = {.lex_state = 24},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 24},
  [48] = {.lex_state = 24},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 50},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 50},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 1},
  [80] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_line_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_opcode] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_operand_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DOTinclude] = ACTIONS(1),
    [anon_sym_DOTproc] = ACTIONS(1),
    [anon_sym_DOTendproc] = ACTIONS(1),
    [sym_immediate] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(61),
    [sym_section] = STATE(13),
    [sym_instruction] = STATE(13),
    [sym_constant] = STATE(13),
    [sym_label] = STATE(7),
    [sym_macro] = STATE(13),
    [sym_macro_include] = STATE(44),
    [sym_macro_proc] = STATE(44),
    [sym_line_comment] = STATE(1),
    [aux_sym_program_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_opcode] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_DOTinclude] = ACTIONS(15),
    [anon_sym_DOTproc] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(19),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(21),
  },
  [2] = {
    [sym_section] = STATE(39),
    [sym_subsection] = STATE(39),
    [sym_instruction] = STATE(39),
    [sym_label] = STATE(10),
    [sym_sublabel] = STATE(19),
    [sym_macro] = STATE(39),
    [sym_macro_include] = STATE(28),
    [sym_macro_proc] = STATE(28),
    [sym_line_comment] = STATE(2),
    [aux_sym_macro_proc_repeat1] = STATE(5),
    [sym_opcode] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [aux_sym_operand_token1] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(29),
    [anon_sym_DOTinclude] = ACTIONS(31),
    [anon_sym_DOTproc] = ACTIONS(33),
    [anon_sym_DOTendproc] = ACTIONS(35),
    [anon_sym_SEMI] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(37),
  },
  [3] = {
    [sym_section] = STATE(39),
    [sym_subsection] = STATE(39),
    [sym_instruction] = STATE(39),
    [sym_label] = STATE(10),
    [sym_sublabel] = STATE(19),
    [sym_macro] = STATE(39),
    [sym_macro_include] = STATE(28),
    [sym_macro_proc] = STATE(28),
    [sym_line_comment] = STATE(3),
    [aux_sym_macro_proc_repeat1] = STATE(4),
    [sym_opcode] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [aux_sym_operand_token1] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(29),
    [anon_sym_DOTinclude] = ACTIONS(31),
    [anon_sym_DOTproc] = ACTIONS(33),
    [anon_sym_DOTendproc] = ACTIONS(39),
    [anon_sym_SEMI] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(37),
  },
  [4] = {
    [sym_section] = STATE(39),
    [sym_subsection] = STATE(39),
    [sym_instruction] = STATE(39),
    [sym_label] = STATE(10),
    [sym_sublabel] = STATE(19),
    [sym_macro] = STATE(39),
    [sym_macro_include] = STATE(28),
    [sym_macro_proc] = STATE(28),
    [sym_line_comment] = STATE(4),
    [aux_sym_macro_proc_repeat1] = STATE(5),
    [sym_opcode] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [aux_sym_operand_token1] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(29),
    [anon_sym_DOTinclude] = ACTIONS(31),
    [anon_sym_DOTproc] = ACTIONS(33),
    [anon_sym_DOTendproc] = ACTIONS(41),
    [anon_sym_SEMI] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(37),
  },
  [5] = {
    [sym_section] = STATE(39),
    [sym_subsection] = STATE(39),
    [sym_instruction] = STATE(39),
    [sym_label] = STATE(10),
    [sym_sublabel] = STATE(19),
    [sym_macro] = STATE(39),
    [sym_macro_include] = STATE(28),
    [sym_macro_proc] = STATE(28),
    [sym_line_comment] = STATE(5),
    [aux_sym_macro_proc_repeat1] = STATE(5),
    [sym_opcode] = ACTIONS(43),
    [sym_identifier] = ACTIONS(46),
    [aux_sym_operand_token1] = ACTIONS(49),
    [anon_sym_DOT] = ACTIONS(52),
    [anon_sym_DOTinclude] = ACTIONS(55),
    [anon_sym_DOTproc] = ACTIONS(58),
    [anon_sym_DOTendproc] = ACTIONS(61),
    [anon_sym_SEMI] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(63),
  },
  [6] = {
    [sym_section] = STATE(39),
    [sym_subsection] = STATE(39),
    [sym_instruction] = STATE(39),
    [sym_label] = STATE(10),
    [sym_sublabel] = STATE(19),
    [sym_macro] = STATE(39),
    [sym_macro_include] = STATE(28),
    [sym_macro_proc] = STATE(28),
    [sym_line_comment] = STATE(6),
    [aux_sym_macro_proc_repeat1] = STATE(2),
    [sym_opcode] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [aux_sym_operand_token1] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(29),
    [anon_sym_DOTinclude] = ACTIONS(31),
    [anon_sym_DOTproc] = ACTIONS(33),
    [anon_sym_DOTendproc] = ACTIONS(66),
    [anon_sym_SEMI] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(37),
  },
  [7] = {
    [sym__section_body] = STATE(8),
    [sym_subsection] = STATE(8),
    [sym_instruction] = STATE(8),
    [sym_sublabel] = STATE(15),
    [sym_macro] = STATE(8),
    [sym_macro_include] = STATE(44),
    [sym_macro_proc] = STATE(44),
    [sym_line_comment] = STATE(7),
    [aux_sym_section_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(68),
    [sym_opcode] = ACTIONS(70),
    [sym_identifier] = ACTIONS(73),
    [aux_sym_operand_token1] = ACTIONS(75),
    [anon_sym_DOT] = ACTIONS(77),
    [anon_sym_DOTinclude] = ACTIONS(80),
    [anon_sym_DOTproc] = ACTIONS(83),
    [anon_sym_SEMI] = ACTIONS(68),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(86),
  },
  [8] = {
    [sym__section_body] = STATE(9),
    [sym_subsection] = STATE(9),
    [sym_instruction] = STATE(9),
    [sym_sublabel] = STATE(15),
    [sym_macro] = STATE(9),
    [sym_macro_include] = STATE(44),
    [sym_macro_proc] = STATE(44),
    [sym_line_comment] = STATE(8),
    [aux_sym_section_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(89),
    [sym_opcode] = ACTIONS(91),
    [sym_identifier] = ACTIONS(94),
    [aux_sym_operand_token1] = ACTIONS(75),
    [anon_sym_DOT] = ACTIONS(96),
    [anon_sym_DOTinclude] = ACTIONS(99),
    [anon_sym_DOTproc] = ACTIONS(102),
    [anon_sym_SEMI] = ACTIONS(89),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(105),
  },
  [9] = {
    [sym__section_body] = STATE(9),
    [sym_subsection] = STATE(9),
    [sym_instruction] = STATE(9),
    [sym_sublabel] = STATE(15),
    [sym_macro] = STATE(9),
    [sym_macro_include] = STATE(44),
    [sym_macro_proc] = STATE(44),
    [sym_line_comment] = STATE(9),
    [aux_sym_section_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(108),
    [sym_opcode] = ACTIONS(110),
    [sym_identifier] = ACTIONS(113),
    [aux_sym_operand_token1] = ACTIONS(115),
    [anon_sym_DOT] = ACTIONS(118),
    [anon_sym_DOTinclude] = ACTIONS(121),
    [anon_sym_DOTproc] = ACTIONS(124),
    [anon_sym_SEMI] = ACTIONS(108),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(127),
  },
  [10] = {
    [sym__section_body] = STATE(31),
    [sym_subsection] = STATE(22),
    [sym_instruction] = STATE(22),
    [sym_sublabel] = STATE(19),
    [sym_macro] = STATE(22),
    [sym_macro_include] = STATE(28),
    [sym_macro_proc] = STATE(28),
    [sym_line_comment] = STATE(10),
    [aux_sym_section_repeat1] = STATE(11),
    [sym_opcode] = ACTIONS(130),
    [sym_identifier] = ACTIONS(73),
    [aux_sym_operand_token1] = ACTIONS(133),
    [anon_sym_DOT] = ACTIONS(136),
    [anon_sym_DOTinclude] = ACTIONS(139),
    [anon_sym_DOTproc] = ACTIONS(142),
    [anon_sym_DOTendproc] = ACTIONS(68),
    [anon_sym_SEMI] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(145),
  },
  [11] = {
    [sym__section_body] = STATE(31),
    [sym_subsection] = STATE(22),
    [sym_instruction] = STATE(22),
    [sym_sublabel] = STATE(19),
    [sym_macro] = STATE(22),
    [sym_macro_include] = STATE(28),
    [sym_macro_proc] = STATE(28),
    [sym_line_comment] = STATE(11),
    [aux_sym_section_repeat1] = STATE(12),
    [sym_opcode] = ACTIONS(148),
    [sym_identifier] = ACTIONS(94),
    [aux_sym_operand_token1] = ACTIONS(151),
    [anon_sym_DOT] = ACTIONS(154),
    [anon_sym_DOTinclude] = ACTIONS(157),
    [anon_sym_DOTproc] = ACTIONS(160),
    [anon_sym_DOTendproc] = ACTIONS(89),
    [anon_sym_SEMI] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(163),
  },
  [12] = {
    [sym__section_body] = STATE(31),
    [sym_subsection] = STATE(22),
    [sym_instruction] = STATE(22),
    [sym_sublabel] = STATE(19),
    [sym_macro] = STATE(22),
    [sym_macro_include] = STATE(28),
    [sym_macro_proc] = STATE(28),
    [sym_line_comment] = STATE(12),
    [aux_sym_section_repeat1] = STATE(12),
    [sym_opcode] = ACTIONS(166),
    [sym_identifier] = ACTIONS(113),
    [aux_sym_operand_token1] = ACTIONS(169),
    [anon_sym_DOT] = ACTIONS(172),
    [anon_sym_DOTinclude] = ACTIONS(175),
    [anon_sym_DOTproc] = ACTIONS(178),
    [anon_sym_DOTendproc] = ACTIONS(108),
    [anon_sym_SEMI] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(181),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(9), 1,
      sym_opcode,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_DOTinclude,
    ACTIONS(17), 1,
      anon_sym_DOTproc,
    ACTIONS(19), 1,
      anon_sym_SEMI,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
    ACTIONS(186), 1,
      anon_sym_LF,
    STATE(7), 1,
      sym_label,
    STATE(13), 1,
      sym_line_comment,
    STATE(44), 2,
      sym_macro_include,
      sym_macro_proc,
    STATE(14), 5,
      sym_section,
      sym_instruction,
      sym_constant,
      sym_macro,
      aux_sym_program_repeat1,
  [45] = 12,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(188), 1,
      ts_builtin_sym_end,
    ACTIONS(190), 1,
      sym_opcode,
    ACTIONS(193), 1,
      sym_identifier,
    ACTIONS(196), 1,
      anon_sym_DOT,
    ACTIONS(199), 1,
      anon_sym_DOTinclude,
    ACTIONS(202), 1,
      anon_sym_DOTproc,
    ACTIONS(205), 1,
      anon_sym_SEMI,
    ACTIONS(208), 1,
      anon_sym_LF,
    STATE(7), 1,
      sym_label,
    STATE(44), 2,
      sym_macro_include,
      sym_macro_proc,
    STATE(14), 6,
      sym_section,
      sym_instruction,
      sym_constant,
      sym_macro,
      sym_line_comment,
      aux_sym_program_repeat1,
  [88] = 12,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(213), 1,
      sym_opcode,
    ACTIONS(216), 1,
      sym_identifier,
    ACTIONS(218), 1,
      anon_sym_DOT,
    ACTIONS(221), 1,
      anon_sym_DOTinclude,
    ACTIONS(224), 1,
      anon_sym_DOTproc,
    ACTIONS(227), 1,
      anon_sym_LF,
    STATE(15), 1,
      sym_line_comment,
    STATE(16), 2,
      sym_subsection_body,
      aux_sym_subsection_repeat1,
    STATE(43), 2,
      sym_instruction,
      sym_macro,
    STATE(44), 2,
      sym_macro_include,
      sym_macro_proc,
    ACTIONS(211), 3,
      ts_builtin_sym_end,
      aux_sym_operand_token1,
      anon_sym_SEMI,
  [130] = 12,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(232), 1,
      sym_opcode,
    ACTIONS(235), 1,
      sym_identifier,
    ACTIONS(237), 1,
      anon_sym_DOT,
    ACTIONS(240), 1,
      anon_sym_DOTinclude,
    ACTIONS(243), 1,
      anon_sym_DOTproc,
    ACTIONS(246), 1,
      anon_sym_LF,
    STATE(16), 1,
      sym_line_comment,
    STATE(17), 2,
      sym_subsection_body,
      aux_sym_subsection_repeat1,
    STATE(43), 2,
      sym_instruction,
      sym_macro,
    STATE(44), 2,
      sym_macro_include,
      sym_macro_proc,
    ACTIONS(230), 3,
      ts_builtin_sym_end,
      aux_sym_operand_token1,
      anon_sym_SEMI,
  [172] = 11,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(251), 1,
      sym_opcode,
    ACTIONS(254), 1,
      sym_identifier,
    ACTIONS(256), 1,
      anon_sym_DOT,
    ACTIONS(259), 1,
      anon_sym_DOTinclude,
    ACTIONS(262), 1,
      anon_sym_DOTproc,
    ACTIONS(265), 1,
      anon_sym_LF,
    STATE(43), 2,
      sym_instruction,
      sym_macro,
    STATE(44), 2,
      sym_macro_include,
      sym_macro_proc,
    ACTIONS(249), 3,
      ts_builtin_sym_end,
      aux_sym_operand_token1,
      anon_sym_SEMI,
    STATE(17), 3,
      sym_subsection_body,
      sym_line_comment,
      aux_sym_subsection_repeat1,
  [212] = 14,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(235), 1,
      sym_identifier,
    ACTIONS(268), 1,
      sym_opcode,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(274), 1,
      anon_sym_DOTinclude,
    ACTIONS(277), 1,
      anon_sym_DOTproc,
    ACTIONS(280), 1,
      anon_sym_LF,
    STATE(18), 1,
      sym_line_comment,
    STATE(20), 1,
      aux_sym_subsection_repeat1,
    STATE(37), 1,
      sym_subsection_body,
    ACTIONS(230), 2,
      aux_sym_operand_token1,
      anon_sym_DOTendproc,
    STATE(21), 2,
      sym_instruction,
      sym_macro,
    STATE(28), 2,
      sym_macro_include,
      sym_macro_proc,
  [258] = 14,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(216), 1,
      sym_identifier,
    ACTIONS(283), 1,
      sym_opcode,
    ACTIONS(286), 1,
      anon_sym_DOT,
    ACTIONS(289), 1,
      anon_sym_DOTinclude,
    ACTIONS(292), 1,
      anon_sym_DOTproc,
    ACTIONS(295), 1,
      anon_sym_LF,
    STATE(18), 1,
      aux_sym_subsection_repeat1,
    STATE(19), 1,
      sym_line_comment,
    STATE(37), 1,
      sym_subsection_body,
    ACTIONS(211), 2,
      aux_sym_operand_token1,
      anon_sym_DOTendproc,
    STATE(21), 2,
      sym_instruction,
      sym_macro,
    STATE(28), 2,
      sym_macro_include,
      sym_macro_proc,
  [304] = 13,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(254), 1,
      sym_identifier,
    ACTIONS(298), 1,
      sym_opcode,
    ACTIONS(301), 1,
      anon_sym_DOT,
    ACTIONS(304), 1,
      anon_sym_DOTinclude,
    ACTIONS(307), 1,
      anon_sym_DOTproc,
    ACTIONS(310), 1,
      anon_sym_LF,
    STATE(37), 1,
      sym_subsection_body,
    ACTIONS(249), 2,
      aux_sym_operand_token1,
      anon_sym_DOTendproc,
    STATE(20), 2,
      sym_line_comment,
      aux_sym_subsection_repeat1,
    STATE(21), 2,
      sym_instruction,
      sym_macro,
    STATE(28), 2,
      sym_macro_include,
      sym_macro_proc,
  [348] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(21), 1,
      sym_line_comment,
    ACTIONS(313), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(315), 5,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_DOTendproc,
      anon_sym_LF,
  [370] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(22), 1,
      sym_line_comment,
    ACTIONS(317), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(319), 5,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_DOTendproc,
      anon_sym_LF,
  [392] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(23), 1,
      sym_line_comment,
    ACTIONS(323), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(321), 6,
      ts_builtin_sym_end,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_SEMI,
      anon_sym_LF,
  [412] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(24), 1,
      sym_line_comment,
    ACTIONS(327), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(325), 6,
      ts_builtin_sym_end,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_SEMI,
      anon_sym_LF,
  [432] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(25), 1,
      sym_line_comment,
    ACTIONS(331), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(329), 6,
      ts_builtin_sym_end,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_SEMI,
      anon_sym_LF,
  [452] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(26), 1,
      sym_line_comment,
    ACTIONS(333), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(335), 5,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_DOTendproc,
      anon_sym_LF,
  [474] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(27), 1,
      sym_line_comment,
    ACTIONS(339), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(337), 6,
      ts_builtin_sym_end,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_SEMI,
      anon_sym_LF,
  [494] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(28), 1,
      sym_line_comment,
    ACTIONS(341), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(343), 5,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_DOTendproc,
      anon_sym_LF,
  [516] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(29), 1,
      sym_line_comment,
    ACTIONS(347), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(345), 6,
      ts_builtin_sym_end,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_SEMI,
      anon_sym_LF,
  [536] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(30), 1,
      sym_line_comment,
    ACTIONS(323), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(321), 5,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_DOTendproc,
      anon_sym_LF,
  [558] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(31), 1,
      sym_line_comment,
    ACTIONS(349), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(351), 5,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_DOTendproc,
      anon_sym_LF,
  [580] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(32), 1,
      sym_line_comment,
    ACTIONS(355), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(353), 6,
      ts_builtin_sym_end,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_SEMI,
      anon_sym_LF,
  [600] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(33), 1,
      sym_line_comment,
    ACTIONS(347), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(345), 5,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_DOTendproc,
      anon_sym_LF,
  [622] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(34), 1,
      sym_line_comment,
    ACTIONS(355), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(353), 5,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_DOTendproc,
      anon_sym_LF,
  [644] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(35), 1,
      sym_line_comment,
    ACTIONS(357), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(359), 5,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_DOTendproc,
      anon_sym_LF,
  [666] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(36), 1,
      sym_line_comment,
    ACTIONS(357), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(359), 6,
      ts_builtin_sym_end,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_SEMI,
      anon_sym_LF,
  [686] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(37), 1,
      sym_line_comment,
    ACTIONS(361), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(363), 5,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_DOTendproc,
      anon_sym_LF,
  [708] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(38), 1,
      sym_line_comment,
    ACTIONS(333), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(335), 6,
      ts_builtin_sym_end,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_SEMI,
      anon_sym_LF,
  [728] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(39), 1,
      sym_line_comment,
    ACTIONS(365), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(367), 5,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_DOTendproc,
      anon_sym_LF,
  [750] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(40), 1,
      sym_line_comment,
    ACTIONS(327), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(325), 5,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_DOTendproc,
      anon_sym_LF,
  [772] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(41), 1,
      sym_line_comment,
    ACTIONS(331), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(329), 5,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_DOTendproc,
      anon_sym_LF,
  [794] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(42), 1,
      sym_line_comment,
    ACTIONS(339), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(337), 5,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_DOTendproc,
      anon_sym_LF,
  [816] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(43), 1,
      sym_line_comment,
    ACTIONS(313), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(315), 6,
      ts_builtin_sym_end,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_SEMI,
      anon_sym_LF,
  [836] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(44), 1,
      sym_line_comment,
    ACTIONS(341), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(343), 6,
      ts_builtin_sym_end,
      aux_sym_operand_token1,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_SEMI,
      anon_sym_LF,
  [856] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(45), 1,
      sym_line_comment,
    ACTIONS(371), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(369), 5,
      ts_builtin_sym_end,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_SEMI,
      anon_sym_LF,
  [875] = 8,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(375), 1,
      sym_immediate,
    ACTIONS(377), 1,
      anon_sym_LF,
    STATE(46), 1,
      sym_line_comment,
    STATE(56), 1,
      sym_operand,
    STATE(59), 1,
      sym_operands,
    ACTIONS(373), 3,
      sym_identifier,
      aux_sym_operand_token1,
      sym_string,
  [902] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(47), 1,
      sym_line_comment,
    ACTIONS(381), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(379), 5,
      ts_builtin_sym_end,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_SEMI,
      anon_sym_LF,
  [921] = 4,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(48), 1,
      sym_line_comment,
    ACTIONS(385), 3,
      sym_opcode,
      sym_identifier,
      anon_sym_DOT,
    ACTIONS(383), 5,
      ts_builtin_sym_end,
      anon_sym_DOTinclude,
      anon_sym_DOTproc,
      anon_sym_SEMI,
      anon_sym_LF,
  [940] = 8,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(375), 1,
      sym_immediate,
    ACTIONS(387), 1,
      anon_sym_LF,
    STATE(49), 1,
      sym_line_comment,
    STATE(56), 1,
      sym_operand,
    STATE(69), 1,
      sym_operands,
    ACTIONS(373), 3,
      sym_identifier,
      aux_sym_operand_token1,
      sym_string,
  [967] = 7,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(375), 1,
      sym_immediate,
    STATE(50), 1,
      sym_line_comment,
    STATE(56), 1,
      sym_operand,
    STATE(63), 1,
      sym_operands,
    ACTIONS(373), 3,
      sym_identifier,
      aux_sym_operand_token1,
      sym_string,
  [991] = 7,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(375), 1,
      sym_immediate,
    STATE(51), 1,
      sym_line_comment,
    STATE(56), 1,
      sym_operand,
    STATE(72), 1,
      sym_operands,
    ACTIONS(373), 3,
      sym_identifier,
      aux_sym_operand_token1,
      sym_string,
  [1015] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(391), 1,
      sym_immediate,
    STATE(47), 1,
      sym_operand,
    STATE(52), 1,
      sym_line_comment,
    ACTIONS(389), 3,
      sym_identifier,
      aux_sym_operand_token1,
      sym_string,
  [1036] = 6,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(375), 1,
      sym_immediate,
    STATE(53), 1,
      sym_line_comment,
    STATE(57), 1,
      sym_operand,
    ACTIONS(373), 3,
      sym_identifier,
      aux_sym_operand_token1,
      sym_string,
  [1057] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(393), 1,
      anon_sym_EQ,
    ACTIONS(395), 1,
      anon_sym_COLON,
    STATE(54), 1,
      sym_line_comment,
  [1073] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(55), 1,
      sym_line_comment,
    ACTIONS(369), 2,
      anon_sym_COMMA,
      anon_sym_LF,
  [1087] = 5,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(397), 1,
      anon_sym_COMMA,
    ACTIONS(399), 1,
      anon_sym_LF,
    STATE(56), 1,
      sym_line_comment,
  [1103] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(401), 1,
      anon_sym_LF,
    STATE(57), 1,
      sym_line_comment,
  [1116] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(403), 1,
      anon_sym_LF,
    STATE(58), 1,
      sym_line_comment,
  [1129] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(405), 1,
      anon_sym_LF,
    STATE(59), 1,
      sym_line_comment,
  [1142] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(407), 1,
      anon_sym_LF,
    STATE(60), 1,
      sym_line_comment,
  [1155] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(409), 1,
      ts_builtin_sym_end,
    STATE(61), 1,
      sym_line_comment,
  [1168] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(411), 1,
      anon_sym_COLON,
    STATE(62), 1,
      sym_line_comment,
  [1181] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(413), 1,
      anon_sym_LF,
    STATE(63), 1,
      sym_line_comment,
  [1194] = 4,
    ACTIONS(415), 1,
      anon_sym_SEMI,
    ACTIONS(417), 1,
      aux_sym_line_comment_token1,
    ACTIONS(419), 1,
      sym_block_comment,
    STATE(64), 1,
      sym_line_comment,
  [1207] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(421), 1,
      sym_string,
    STATE(65), 1,
      sym_line_comment,
  [1220] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(423), 1,
      sym_identifier,
    STATE(66), 1,
      sym_line_comment,
  [1233] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(425), 1,
      sym_string,
    STATE(67), 1,
      sym_line_comment,
  [1246] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(427), 1,
      anon_sym_LF,
    STATE(68), 1,
      sym_line_comment,
  [1259] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(429), 1,
      anon_sym_LF,
    STATE(69), 1,
      sym_line_comment,
  [1272] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(431), 1,
      anon_sym_LF,
    STATE(70), 1,
      sym_line_comment,
  [1285] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(433), 1,
      anon_sym_LF,
    STATE(71), 1,
      sym_line_comment,
  [1298] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(435), 1,
      anon_sym_LF,
    STATE(72), 1,
      sym_line_comment,
  [1311] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(437), 1,
      anon_sym_COLON,
    STATE(73), 1,
      sym_line_comment,
  [1324] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(439), 1,
      anon_sym_LF,
    STATE(74), 1,
      sym_line_comment,
  [1337] = 4,
    ACTIONS(415), 1,
      anon_sym_SEMI,
    ACTIONS(419), 1,
      sym_block_comment,
    ACTIONS(441), 1,
      aux_sym_line_comment_token1,
    STATE(75), 1,
      sym_line_comment,
  [1350] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(443), 1,
      anon_sym_LF,
    STATE(76), 1,
      sym_line_comment,
  [1363] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(445), 1,
      anon_sym_LF,
    STATE(77), 1,
      sym_line_comment,
  [1376] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(447), 1,
      anon_sym_COLON,
    STATE(78), 1,
      sym_line_comment,
  [1389] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(449), 1,
      sym_identifier,
    STATE(79), 1,
      sym_line_comment,
  [1402] = 1,
    ACTIONS(383), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 45,
  [SMALL_STATE(15)] = 88,
  [SMALL_STATE(16)] = 130,
  [SMALL_STATE(17)] = 172,
  [SMALL_STATE(18)] = 212,
  [SMALL_STATE(19)] = 258,
  [SMALL_STATE(20)] = 304,
  [SMALL_STATE(21)] = 348,
  [SMALL_STATE(22)] = 370,
  [SMALL_STATE(23)] = 392,
  [SMALL_STATE(24)] = 412,
  [SMALL_STATE(25)] = 432,
  [SMALL_STATE(26)] = 452,
  [SMALL_STATE(27)] = 474,
  [SMALL_STATE(28)] = 494,
  [SMALL_STATE(29)] = 516,
  [SMALL_STATE(30)] = 536,
  [SMALL_STATE(31)] = 558,
  [SMALL_STATE(32)] = 580,
  [SMALL_STATE(33)] = 600,
  [SMALL_STATE(34)] = 622,
  [SMALL_STATE(35)] = 644,
  [SMALL_STATE(36)] = 666,
  [SMALL_STATE(37)] = 686,
  [SMALL_STATE(38)] = 708,
  [SMALL_STATE(39)] = 728,
  [SMALL_STATE(40)] = 750,
  [SMALL_STATE(41)] = 772,
  [SMALL_STATE(42)] = 794,
  [SMALL_STATE(43)] = 816,
  [SMALL_STATE(44)] = 836,
  [SMALL_STATE(45)] = 856,
  [SMALL_STATE(46)] = 875,
  [SMALL_STATE(47)] = 902,
  [SMALL_STATE(48)] = 921,
  [SMALL_STATE(49)] = 940,
  [SMALL_STATE(50)] = 967,
  [SMALL_STATE(51)] = 991,
  [SMALL_STATE(52)] = 1015,
  [SMALL_STATE(53)] = 1036,
  [SMALL_STATE(54)] = 1057,
  [SMALL_STATE(55)] = 1073,
  [SMALL_STATE(56)] = 1087,
  [SMALL_STATE(57)] = 1103,
  [SMALL_STATE(58)] = 1116,
  [SMALL_STATE(59)] = 1129,
  [SMALL_STATE(60)] = 1142,
  [SMALL_STATE(61)] = 1155,
  [SMALL_STATE(62)] = 1168,
  [SMALL_STATE(63)] = 1181,
  [SMALL_STATE(64)] = 1194,
  [SMALL_STATE(65)] = 1207,
  [SMALL_STATE(66)] = 1220,
  [SMALL_STATE(67)] = 1233,
  [SMALL_STATE(68)] = 1246,
  [SMALL_STATE(69)] = 1259,
  [SMALL_STATE(70)] = 1272,
  [SMALL_STATE(71)] = 1285,
  [SMALL_STATE(72)] = 1298,
  [SMALL_STATE(73)] = 1311,
  [SMALL_STATE(74)] = 1324,
  [SMALL_STATE(75)] = 1337,
  [SMALL_STATE(76)] = 1350,
  [SMALL_STATE(77)] = 1363,
  [SMALL_STATE(78)] = 1376,
  [SMALL_STATE(79)] = 1389,
  [SMALL_STATE(80)] = 1402,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_proc_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_proc_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_proc_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_proc_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_proc_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_proc_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_macro_proc_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_proc_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_section, 1, 0, 0), SHIFT(46),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_section, 1, 0, 0), SHIFT(66),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 1, 0, 0), SHIFT(65),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 1, 0, 0), SHIFT(60),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 1, 0, 0), SHIFT(8),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 1),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_section, 2, 0, 1), SHIFT(46),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 2, 0, 1),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_section, 2, 0, 1), SHIFT(66),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 2, 0, 1), SHIFT(65),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 2, 0, 1), SHIFT(60),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 2, 0, 1), SHIFT(9),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_section, 1, 0, 0), SHIFT(49),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 1, 0, 0), SHIFT(78),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_section, 1, 0, 0), SHIFT(79),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 1, 0, 0), SHIFT(67),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 1, 0, 0), SHIFT(76),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 1, 0, 0), SHIFT(22),
  [148] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_section, 2, 0, 1), SHIFT(49),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 2, 0, 1), SHIFT(78),
  [154] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_section, 2, 0, 1), SHIFT(79),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 2, 0, 1), SHIFT(67),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 2, 0, 1), SHIFT(76),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 2, 0, 1), SHIFT(22),
  [166] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [172] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [190] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [193] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [196] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [199] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subsection, 1, 0, 0),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_subsection, 1, 0, 0), SHIFT(46),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subsection, 1, 0, 0),
  [218] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_subsection, 1, 0, 0), SHIFT(66),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_subsection, 1, 0, 0), SHIFT(65),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_subsection, 1, 0, 0), SHIFT(60),
  [227] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_subsection, 1, 0, 0), SHIFT(43),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subsection, 2, 0, 1),
  [232] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_subsection, 2, 0, 1), SHIFT(46),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subsection, 2, 0, 1),
  [237] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_subsection, 2, 0, 1), SHIFT(66),
  [240] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_subsection, 2, 0, 1), SHIFT(65),
  [243] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_subsection, 2, 0, 1), SHIFT(60),
  [246] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_subsection, 2, 0, 1), SHIFT(43),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subsection_repeat1, 2, 0, 0),
  [251] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_subsection_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [254] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_subsection_repeat1, 2, 0, 0),
  [256] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_subsection_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [259] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subsection_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [262] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subsection_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [265] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subsection_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [268] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_subsection, 2, 0, 1), SHIFT(49),
  [271] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_subsection, 2, 0, 1), SHIFT(79),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_subsection, 2, 0, 1), SHIFT(67),
  [277] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_subsection, 2, 0, 1), SHIFT(76),
  [280] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_subsection, 2, 0, 1), SHIFT(21),
  [283] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_subsection, 1, 0, 0), SHIFT(49),
  [286] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_subsection, 1, 0, 0), SHIFT(79),
  [289] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_subsection, 1, 0, 0), SHIFT(67),
  [292] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_subsection, 1, 0, 0), SHIFT(76),
  [295] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_subsection, 1, 0, 0), SHIFT(21),
  [298] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_subsection_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [301] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_subsection_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [304] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subsection_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [307] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subsection_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [310] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subsection_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subsection_body, 1, 0, 0),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subsection_body, 1, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__section_body, 1, 0, 0),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__section_body, 1, 0, 0),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, 0, 0),
  [323] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 2, 0, 0),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 4, 0, 0),
  [327] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 4, 0, 0),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_proc, 4, 0, 2),
  [331] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_proc, 4, 0, 2),
  [333] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_include, 2, 0, 0),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_include, 2, 0, 0),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sublabel, 3, 0, 0),
  [339] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sublabel, 3, 0, 0),
  [341] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 1, 0, 0),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 1, 0, 0),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 3, 0, 0),
  [347] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 3, 0, 0),
  [349] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 1, 0, 0),
  [351] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 1, 0, 0),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 3, 0, 0),
  [355] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label, 3, 0, 0),
  [357] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_proc, 3, 0, 0),
  [359] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_proc, 3, 0, 0),
  [361] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_subsection_repeat1, 1, 0, 0),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subsection_repeat1, 1, 0, 0),
  [365] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_macro_proc_repeat1, 1, 0, 0),
  [367] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_macro_proc_repeat1, 1, 0, 0),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operand, 1, 0, 0),
  [371] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operand, 1, 0, 0),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [375] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [379] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 3, 0, 0),
  [381] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 3, 0, 0),
  [383] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 3, 0, 0),
  [385] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_comment, 3, 0, 0),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [391] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [399] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operands, 1, 0, 0),
  [401] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operands, 3, 0, 0),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [409] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [415] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [417] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [419] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [423] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [425] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [427] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [429] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [431] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [433] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [435] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [437] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [439] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [441] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [443] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [445] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [447] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [449] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ca65(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
